### ISSUE TITLE
add docker support

### ISSUE THREAD

**Issue by danaronson** [mitra42/bct-server#15]
Use ansible to deploy:

- server
- nginx or apache front end (ssl support, etc)
- supervisord to run and log server
- letsencrypt cert and crontab to update

**Comment by mitra42** [comment]
Do you think that's the right way, or would it be better to use Docker instead of Ansible, I suspect these will want to run in their own virtual servers so we don't have to be as concerned about security of the data from other things running on the same box ? 

Or Kubernetes (as at the Archive) where ingress acts as a the ssl front end and can spawn up the Dockers. 

But ... I think you know that stuff better than me ?

**Comment by danaronson** [comment]
ok... i've been avoiding learning kubernetes... perhaps it's time. In
general when i use clouds (particularly aws they are all virtual servers
anyway).

--dan

**Comment by mitra42** [comment]
Its got a tough learning curve, but even without K8, Docker would probably be worth it, so new servers could be spun up quickly ? I find that Docker is as easy to configure for as most other things. I haven't tried using ansible Plus Docker, not sure if there is any advantage (I can't get my head around ansible ! ) . 

If you do try K8, Tracey is a good resource as she did the Archives.

**Comment by danaronson** [comment]
ok, i'm going to go with docker
